### ISSUE TITLE
 error  in ./node_modules/vue-jsmpeg-player/dist/jsmpeg-player.umd.min.js

### ISSUE THREAD

**Issue by ywwtx** [vCloudSail/jsmpeg-player#1]
@vCloudSail 
 ERROR  Failed to compile with 1 error                                                                                                                        17:45:56

 error  in ./node_modules/vue-jsmpeg-player/dist/jsmpeg-player.umd.min.js

Module parse failed: Unexpected token (1:34510)
class Q{constructor(A){r(this,"canvas",void 0),this.canvas=A.canvas??document.createElement("canvas") 这个里面有双问号，编译出错。

**Comment by vCloudSail** [comment]
使用了es2020的可选链操作符?.以及空值合并操作符??，如果编译报错的话检查下core-js版本

**Comment by ywwtx** [comment]
"@jiaminghi/data-view": "^2.10.0",
    "@riophae/vue-treeselect": "0.4.0",
    "axios": "0.24.0",
    "clipboard": "2.0.8",
    "core-js": "3.24.1",
    "echarts": "4.9.0", 
    "element-ui": "2.15.8",

刚看了下，是最新版本了，还有可能和那些有关系？我用的是ruoyi-vue 把element-ui 和vue的版本都升了

**Comment by vCloudSail** [comment]
之前没空回你，你试下安装@babel/core这个插件，后续我把这几个语法去掉再发布一版吧
![image](https://user-images.githubusercontent.com/45616923/184302848-e545d69f-6c74-422e-9050-3dc5dff1ba25.png)

**Comment by vCloudSail** [comment]
@ywwtx core-js设置为dependencies后问题解决，可安装1.0.1-beta再试下
