### ISSUE TITLE
安装引入项目报错

### ISSUE THREAD

**Issue by mlzk** [vCloudSail/jsmpeg-player#3]
`./node_modules/vue-jsmpeg-player/dist/jsmpeg-player.umd.js 3279:34
Module parse failed: Unexpected token (3279:34)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|     _defineProperty(this, "canvas", void 0);
| 
>     this.canvas = options.canvas ?? document.createElement('canvas');
|     this.width = this.canvas.width;
|     this.height = this.canvas.height;`

jsmpeg-player.umd.js/jsmpeg-player.umd.min.js/...

都会报这个错误，我fork到本地自行打包build:demo可以运行，但是build报同样的错，是还需要额外的loader么？

**Comment by vCloudSail** [comment]
使用了es6+语法，需要安装core-js@3

**Comment by mlzk** [comment]
> 使用了es6+语法，需要安装core-js@3

看到了，目标项目是个老项目，所以我fork之后改了打包的兼容targets，可以了，感谢~
